services:
  postgres_db_sc:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userDemo
      POSTGRES_DB: global_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - global
  pgadmin_sc:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "7000:80"
    depends_on:
      - postgres_db_sc
    networks:
      - global

networks:
  global:
    driver: bridge