spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: ${APP_ACTIVE_PROFILE :dev}
  application:
    name: Global Sphere
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    mail-reset-password-url: ${MAIL_RESET_PASSWORD_URL} #my custom prop
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: ${APP_PORT}
custom:
  populate_db: ${APP_POPULATE :true}
