spring:
  profiles:
    active: ${APP_ACTIVE_PROFILE :dev}
  application:
    name: Global Sphere
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: ${APP_PORT}
custom:
  populate_db: ${APP_POPULATE :false}
