# DATABASE
DB_USERNAME: ${DB_USERNAME}
DB_PASSWORD: ${DB_PASSWORD}
DB_PORT: ${DB_PORT}
DB_HOST: ${DB_HOST}
DB: ${DB}

#APP
APP_PORT: ${APP_PORT}
APP_ACTIVE_PROFILE: ${APP_ACTIVE_PROFILE :prod}
APP_POPULATE: ${APP_POPULATE :false}

#EMAIL
MAIL_PORT: ${MAIL_PORT}
MAIL_HOST: ${MAIL_HOST}
MAIL_USERNAME: ${MAIL_USERNAME}
MAIL_PASSWORD: ${MAIL_PASSWORD}
MAIL_RESET_PASSWORD_URL: ${MAIL_RESET_PASSWORD_URL}
MAIL_ENABLE: ${MAIL_ENABLE :true} #now not being used
